# Generated by Django 5.2.4 on 2025-07-19 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['-valid_from'], 'verbose_name': 'купон', 'verbose_name_plural': 'купоны'},
        ),
        migrations.AddField(
            model_name='coupon',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='applied_coupons', to='orders.order', verbose_name='заказы с этим купоном'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='active',
            field=models.BooleanField(default=True, help_text='Активен ли купон для использования', verbose_name='активен'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(help_text='Уникальный код купона', max_length=50, unique=True, verbose_name='код купона'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.PositiveIntegerField(help_text='Процент скидки (от 1 до 100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='размер скидки'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(help_text='Дата начала действия купона', verbose_name='действует с'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(help_text='Дата окончания действия купона', verbose_name='действует до'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code'], name='coupons_cou_code_3bf721_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['valid_from', 'valid_to'], name='coupons_cou_valid_f_cf442c_idx'),
        ),
    ]
